name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/TaskManagerApi/TaskManagerApi.sln
    - name: Build
      run: dotnet build Backend/TaskManagerApi/TaskManagerApi/TaskManagerApi.csproj --no-restore
    - name: Test
      run: dotnet test Backend/TaskManagerApi/TaskManagerApi.sln